import { Injectable } from '@angular/core';

@Injectable()
export class ServerErrorcodeService {

  errorCodes = {
    "IJS_CNTR_EX_99999": "User is not authorized to create contract for selected input(s)",
    "IJS_EX_10001": "There is no record for given search criteria",
    "IJS_EX_10006": "Please change the route.",
    "IJS_EX_10007": "Please change the priority.",
    "IJS_EX_10008": "Vendor code is not valid",
    "IJS_EX_10009": "No record to delete",
    "IJS_EX_10010": "No record to suspend",
    "IJS_EX_10011": "Cost rate app failed",
    "IJS_EX_10012": "Cost rate delete failed",
    "IJS_EX_10013": "Cost rate rejected failed",
    "IJS_EX_10014": "Add cost rate failed",
    "IJS_EX_10015": "Update cost rate failed",
    "IJS_EX_10016": "Bill rate app failed",
    "IJS_EX_10017": "Bill rate delete failed",
    "IJS_EX_10018": "Bill rate rejected failed",
    "IJS_EX_10019": "Add Bill Rate record failed",
    "IJS_EX_10020": "Update bill rate failed",
    "IJS_EX_10022": "Cost dates are not lying between Effective and Expiry date of contract",
    "IJS_EX_10023": "Bill dates are not lying between Effective and Expiry date of contract",
    "IJS_EX_10024": "rate should not be negative",
    "IJS_EX_10025": "rate should not be negative",
    "IJS_EX_10026": "Effective Date should not be greater than Expiry Date",
    "IJS_ERR_1021": "Location users cannot Approve or Reject JO",
    "IJS_ERR_1022": "Only waitlisted Job Order(s) can be Approved",
    "IJS_ERR_1023": "Invalid FSC Code",
    "IJS_ERR_1024": "Job Order with Status Issued cannot be Rejected",
    "IJS_EX_10029": "There is an issue with reset,please try again",
    "IJS_EX_10030": "There is an issue with ProcessJO,please try again",
    "IJS_EX_10041": "Record Locked by Another user",
    "IJS_EX_10042": "Error in Creating JO Summary",
    "IJS_EX_10043": "No Container Available",
    "IJS_EX_10031": "Rate Not Found for Booking/BL:",
    "IJS_ADHOC_10031": "Rate Not Found for the selected container(s).",
    "IJS_EX_10032": "JO Cost calculation Failed.",
    "IJS_EX_10033": "There is an issue on exchange rate processing.",
    "IJS_EX_10034": "There is an issue on cost saving.",
    "IJS_EX_10035": "Vendor is changed successfully.",
    "IJS_EX_10044": "Duplicate Route Exists",
    "IJS_EX_10045": "Date is not valid(DD/MM/YYYY)",
    "IJS_EX_10046": "Contract already existed for the same route for this vendor",
    "IJS_CNTR_EX_10019": "Bill rate add failed",
    "IJS_CNTR_EX_10020": "Bill rate update failed",
    "IJS_CNTR_EX_10032": "Expiry Date should not be less than Current Date",
    "IJS_CNTR_EX_10033": "Invalid Vendor code",
    "IJS_MSG_1001": "Record successfully inserted",
    "IJS_MSG_1002": "Record successfully updated",
    "IJS_MSG_1003": "Record successfully deleted",
    "IJS_MSG_1004": "Contract Date expired",
    "IJS_MSG_1005": "Contract Suspended",
    "IJS_MSG_1006": "Cost Rate record successfully approved",
    "IJS_MSG_1007": "Cost Rate record successfully deleted",
    "IJS_MSG_1008": "Cost Rate record successfully rejected",
    "IJS_MSG_1009": "Cost Rate record successfully added",
    "IJS_MSG_1010": "Cost Rate record successfully updated",
    "IJS_MSG_1011": "Cost Rate record successfully updated",
    "IJS_MSG_1012": "Bill rate successfully rejected",
    "IJS_MSG_1013": "Bill Rate record successfully added",
    "IJS_MSG_1014": "Bill Rate record successfully updated",
    "IJS_MSG_1015": "Bill Rate updated Suceessfully",
    "IJS_MSG_1016": "Job Order(s) Cancelled Successfully",
    "IJS_MSG_1017": " Job Order(s) Rejected Successfully",
    "IJS_MSG_1018": " Job Order(s) Approved Successfully",
    "IJS_MSG_1019": " Job Order(s) Completed Successfully",
    "IJS_MSG_1020": " Booking/BL cannot be deleted for Single Record",
    "IJS_MSG_1021": " Error occured while deleting",
    "IJS_MSG_1022": " Delete success",
    "IJS_MSG_1023": " No Containers is Valid",
    "IJS_EX_10047": " Invalid Vendor Code",
    "IJS_EX_10048": " Invalid FSC Code",
    "IJS_EX_10049": " Invalid Terminal Code",
    "UI_IJS_UPLD_EX_10001" : " Contract Uploaded Successfully.",
    "UI_IJS_UPLD_EX_10002" : " Contract Upload Partially Successfull or Unsuccessfull.",
  "IJS_CNTR_EX_10031" : " Auto calculated max Priority(99) is already assigned.",
   "IJS_CNTR_EX_10034" : "Generate Port Pair is already done,this action can be performed again after",
    "IJS_RATE_EX_10016" : " Record already existed.",
    "IJS_RATE_EX_10017" : " Different records can not be merged.",
    "IJS_RATE_EX_10018" : " Port class code is not valid.",
    "IJS_RATE_EX_10019" : " IMDG class code is not valid.",
    "IJS_RATE_EX_10020" : " Please select either only '**' or rest of the equipment type(s).",
    "IJS_CNTR_JO_EX_1001" : " Active JO exist,selected contract(s) can not be suspended.",
    "IJS_CNTR_JO_EX_1002" : " Active JO exist,selected contract(s) can not be deleted.",
    "GBL_IJS_EX_10001" : "There is DB connection issue.Please try again.",
    "IJS_PRJ_EX_10001" :"Vendor code is invalid.",
    "IJS_PRJ_EX_10002" :"Vendor doesn't have routing for the selected search combination.",
    "IJS_PRJ_EX_10003" :"Equipment doesn't exist.",
    "IJS_PRJ_EX_10004" :"Equipment location doesn't match with the From location of contract.",
    "IJS_PRJ_EX_10005" :"JO is already created and Equipment can not be used to move back to the source location .",
    "IJS_PRJ_EX_10006" :"JO is already created with this equipment.",
    "IJS_COMM_EX_1" :"Correct negative values.",
    "IJS_COMM_SETUP_EX_1001" :"From and To Location should be either in same country or there should be a setup for From and To Location combination.",
    "NO_RATE_AVAILABLE": "No rate for deleted Lumpsum JO,Please process jo summary again.",
    "IJS_RATE_EX_10021": "Service code is not valid.",
    "IJS_RATE_EX_10022": "Vessel code is not valid.",
    "IJS_RATE_EX_10023": "Currency code is not valid.",
    "IJS_RATE_EX_10024": "Rate Type is not setup for the selected special handling."
  }

  constructor() { }

  checkError(errorCode) {
    return this.errorCodes[errorCode];
  }

}
